[project]
name = "multicourse-project-m2-last"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "kagglehub[pandas-datasets]>=0.4.0",
    "pandas>=2.3.3",
]
