[project]
name = "recommandation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pykeen>=1.11.1",
    "rdflib>=7.5.0",
    "streamlit>=1.53.0",
    "torch>=2.9.1",
]
